import type { Base } from "./types";

/** Données d'exemple (fictives) chargées au premier démarrage. */
export function exemple(): Base {
  const maintenant = new Date().toISOString();
  return {
    prochainNumero: 26,
    contacts: [
      {
        id: "c-logeo",
        type: "entreprise",
        nom: "Contact Logéo",
        societe: "Logéo Seine",
        email: "contact@exemple.fr",
        telephone: "02 00 00 00 00",
        adresse: "139 Cours de la République, 76600 Le Havre",
        siret: "36750089900201",
        acompte: true,
        emailFacturation: "factures@exemple.fr",
        creeLe: maintenant,
      },
      {
        id: "c-riva",
        type: "entreprise",
        nom: "Contact Riva",
        societe: "Riva",
        email: "riva@exemple.fr",
        telephone: "02 00 00 00 01",
        adresse: "Le Havre",
        acompte: false,
        notes: "Client habituel, pas d'acompte.",
        creeLe: maintenant,
      },
      {
        id: "c-martin",
        type: "particulier",
        nom: "Famille Martin",
        email: "martin@exemple.fr",
        telephone: "06 00 00 00 02",
        adresse: "Le Havre",
        acompte: true,
        creeLe: maintenant,
      },
      {
        id: "c-leguellec",
        type: "particulier",
        nom: "M. et Mme Le Guellec",
        email: "leguellec@exemple.fr",
        telephone: "06 00 00 00 03",
        adresse: "Le Havre",
        acompte: true,
        creeLe: maintenant,
      },
    ],
    devis: [
      {
        id: "d-25",
        numero: "DV0000025",
        contactId: "c-logeo",
        titre: "Réunion entreprise",
        dateEvenement: "2026-10-15",
        heure: "12:00",
        lieu: "139 Cours de la République, Le Havre",
        invites: 50,
        formule: "Cocktail 6 pièces, livré",
        regimes: "3 végétariens · 1 allergie aux fruits à coque · 1 sans gluten",
        deroule:
          "11 h 00 · arrivée de l'équipe, installation du buffet\n12 h 00 · ouverture du cocktail\n12 h 45 · pièces sucrées\n13 h 30 · débarrassage et départ",
        numeroCommande: "1-2026016565",
        etape: "envoye",
        acomptePct: 20,
        creeLe: "2026-10-02T09:00:00.000Z",
        lignes: [
          { id: "l1", chapitre: "Restauration", designation: "Cocktail 6 pièces", quantite: 65, prixUnitaireHT: 9, tva: 10 },
          { id: "l2", chapitre: "Restauration", designation: "Pièces sucrées", quantite: 50, prixUnitaireHT: 5.85, tva: 10 },
          { id: "l3", chapitre: "Logistique", designation: "Forfait livraison ≤ 15 km", quantite: 1, prixUnitaireHT: 30, tva: 20 },
        ],
      },
      {
        id: "d-22",
        numero: "DV0000022",
        contactId: "c-riva",
        titre: "Privatisation Riva",
        dateEvenement: "2026-10-08",
        heure: "19:00",
        lieu: "Salle Riva, Le Havre",
        invites: 40,
        formule: "Cocktail dînatoire",
        regimes: "",
        deroule: "",
        etape: "signe",
        acomptePct: 20,
        creeLe: "2026-09-20T09:00:00.000Z",
        lignes: [
          { id: "l1", chapitre: "Restauration", designation: "Cocktail dînatoire", quantite: 40, prixUnitaireHT: 32, tva: 10 },
        ],
      },
      {
        id: "d-23",
        numero: "DV0000023",
        contactId: "c-martin",
        titre: "Mariage Martin",
        dateEvenement: "2026-10-10",
        heure: "18:00",
        lieu: "Parc de Rouelles, Le Havre",
        invites: 66,
        formule: "Cocktail + repas",
        regimes: "2 végétariens",
        deroule: "",
        etape: "signe",
        acomptePct: 20,
        creeLe: "2026-09-10T09:00:00.000Z",
        lignes: [
          { id: "l1", chapitre: "Restauration", designation: "Repas de mariage", quantite: 66, prixUnitaireHT: 28, tva: 10 },
        ],
      },
      {
        id: "d-24",
        numero: "DV0000024",
        contactId: "c-leguellec",
        titre: "Anniversaire plancha",
        dateEvenement: "2026-10-10",
        heure: "12:30",
        lieu: "Le Havre",
        invites: 50,
        formule: "Plancha",
        regimes: "",
        deroule: "",
        etape: "predevis",
        acomptePct: 20,
        creeLe: "2026-10-01T09:00:00.000Z",
        lignes: [],
      },
    ],
  };
}
